/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Gerencia;

import Control.Gerencia.ControlDeletarConta;
import DAO.Gerencia.ClienteDAO;
import Entity.Gerencia.Cliente;
import Entity.Gerencia.Conta;
import java.util.List;

/**
 *
 * @author amiltonjunior
 */
public class FrameDeletarConta extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private FrameBemVindo parentFrame;
//    private Map<Integer, Map<String, ArrayList<String>>> bdClientes;

    private List<Cliente> clientes;

    /**
     * Creates new form FrameDeletarConta
     */
    public FrameDeletarConta() {
        initComponents();
    }

    public void resetCliente() {
        nomeCliente.removeAllItems();
        nomeCliente.addItem("- Selecione -");
        nomeCliente.setSelectedIndex(0);
    }

    public void resetConta() {
        try {
            cmbConta.removeAllItems();
        } catch (Exception e) {
        }

        cmbConta.addItem("- Selecione -");
        cmbConta.setSelectedIndex(0);
    }

    public void resetStatus() {
        status.setText("---");
    }

    public void preencherNomesClientes() {
        // Limpa os campos
        ControlDeletarConta.limparCampos(this);

        // Preenche com os nomes dos clientes
        ClienteDAO.getInstance().getEntity().clear();
        clientes = ClienteDAO.getInstance().findAll();

        for (Cliente cliente : clientes) {
            nomeCliente.addItem(cliente.getNome());
        }
    }

//    public Map<Integer, Map<String, ArrayList<String>>> getBdClientes() {
//        return this.bdClientes;
//    }

    // Método que armazena o JFrame pai
    public void setParentFrame(FrameBemVindo parentFrame) {
        this.parentFrame = parentFrame;
    }

    // Método que retorna o JFrame pai
    public FrameBemVindo getParentFrame() {
        return this.parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal6 = new javax.swing.JPanel();
        lblLogotipo6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        deletar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JComboBox<>();
        cmbConta = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        PainelPrincipal6.setBackground(new java.awt.Color(255, 255, 255));

        lblLogotipo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogotipo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icones/logo_banco.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Banco MM - MoneyMaker");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        deletar.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        deletar.setText("Deletar");
        deletar.setEnabled(false);
        deletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeletarclick(evt);
            }
        });
        deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente:");

        jLabel3.setText("Conta:");

        nomeCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Selecione -" }));
        nomeCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nomeClienteItemStateChanged(evt);
            }
        });
        nomeCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeClienteFocusLost(evt);
            }
        });
        nomeCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomeClienteMouseClicked(evt);
            }
        });
        nomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeClienteclienteChanged(evt);
            }
        });

        cmbConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Selecione -" }));
        cmbConta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbContaFocusLost(evt);
            }
        });
        cmbConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbContaMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbContaMouseClicked(evt);
            }
        });
        cmbConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbContaSelecionada(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("Deletar uma Conta");

        jLabel5.setText("Status:");

        status.setText("[STATUS]");

        javax.swing.GroupLayout PainelPrincipal6Layout = new javax.swing.GroupLayout(PainelPrincipal6);
        PainelPrincipal6.setLayout(PainelPrincipal6Layout);
        PainelPrincipal6Layout.setHorizontalGroup(
            PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(lblLogotipo6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cmbConta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(status))
                                    .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                            .addGap(36, 36, 36)
                                            .addComponent(deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipal6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(237, 237, 237))
        );
        PainelPrincipal6Layout.setVerticalGroup(
            PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLogotipo6)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(42, 42, 42)
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndeletarclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeletarclick
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeletarclick

    private void deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarActionPerformed
        
         int indexCliente = nomeCliente.getSelectedIndex();
        int indexConta = cmbConta.getSelectedIndex();
        
        Conta conta = clientes.get(indexCliente - 1).getConta().get(indexConta - 1);
        
        boolean status = ControlDeletarConta.deletar(conta, deletar.getText());
        
        if (status) {
            ControlDeletarConta.sucesso();

            ControlDeletarConta.cancelar(this, getParentFrame());
        } else {
            ControlDeletarConta.erro();
        }
    }//GEN-LAST:event_deletarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        ControlDeletarConta.cancelar(this, getParentFrame());
    }//GEN-LAST:event_cancelarActionPerformed

    private void nomeClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nomeClienteItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeClienteItemStateChanged

    private void nomeClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeClienteFocusLost
        // Obtém o nome do cliente
        int indexCliente = nomeCliente.getSelectedIndex();
        
        if (indexCliente > 0) {
        
            Cliente cliente = clientes.get(indexCliente - 1);
            resetConta();
            resetStatus();

            for (Conta c : cliente.getConta()) {
                 cmbConta.addItem("AG: " + c.getAgencia() + " CONTA N: " + c.getNumeroConta());
            }
            
        }
    }//GEN-LAST:event_nomeClienteFocusLost

    private void nomeClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeClienteMouseClicked
        resetConta();
        resetStatus();
    }//GEN-LAST:event_nomeClienteMouseClicked

    private void nomeClienteclienteChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeClienteclienteChanged

    }//GEN-LAST:event_nomeClienteclienteChanged

    private void cmbContaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbContaFocusLost

    }//GEN-LAST:event_cmbContaFocusLost

    private void cmbContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbContaMouseClicked

    }//GEN-LAST:event_cmbContaMouseClicked

    private void cmbContaSelecionada(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbContaSelecionada

    }//GEN-LAST:event_cmbContaSelecionada

    private void cmbContaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbContaMouseReleased
        // Obtém a conta selecionada
        int indexCliente = nomeCliente.getSelectedIndex();
        int indexConta = cmbConta.getSelectedIndex();

        if (indexConta > 0) {
            resetStatus();
            
            Conta conta = clientes.get(indexCliente - 1).getConta().get(indexConta - 1);

            // Obtém o status
            String s = conta.getStatus();

            status.setText(s.toUpperCase());
            
            deletar.setEnabled(true);
        }
    }//GEN-LAST:event_cmbContaMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDeletarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDeletarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDeletarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDeletarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDeletarConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPrincipal6;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox<String> cmbConta;
    private javax.swing.JButton deletar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogotipo6;
    private javax.swing.JComboBox<String> nomeCliente;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
