/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Gerencia;

import Control.Gerencia.ControlEstornar;
import DAO.Gerencia.ClienteDAO;
import Entity.Gerencia.Cliente;
import Entity.Gerencia.Conta;
import Entity.Gerencia.Movimentacao;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author amiltonjunior
 */
public class FrameEstornar extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private FrameBemVindo parentFrame;
//    private Map<Integer, Map<String, ArrayList<String>>> bdClientes;

    private List<Cliente> clientes;

    /**
     * Creates new form FrameEstornar
     */
    public FrameEstornar() {
        initComponents();
    }

    public void preencherNomesClientes() {
        // Limpa os campos
        ControlEstornar.limparCampos(this);

        // Preenche com os nomes dos clientes
        ClienteDAO.getInstance().getEntity().clear();
        clientes = ClienteDAO.getInstance().findAll();

        for (Cliente cliente : clientes) {
            nomeCliente.addItem(cliente.getNome());
        }
    }

//    public Map<Integer, Map<String, ArrayList<String>>> getBdClientes() {
//        return this.bdClientes;
//    }
    // Método que armazena o JFrame pai
    public void setParentFrame(FrameBemVindo parentFrame) {
        this.parentFrame = parentFrame;
    }

    // Método que retorna o JFrame pai
    public FrameBemVindo getParentFrame() {
        return this.parentFrame;
    }

    public void resetCliente() {
        nomeCliente.removeAllItems();
        nomeCliente.addItem("- Selecione -");
        nomeCliente.setSelectedIndex(0);
    }

    public void resetConta() {
        conta.removeAllItems();
        conta.addItem("- Selecione -");
        conta.setSelectedIndex(0);
    }

    public void resetLancamento() {
        lancamento.removeAllItems();
        lancamento.addItem("- Selecione -");
        lancamento.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal6 = new javax.swing.JPanel();
        lblLogotipo6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        estornar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JComboBox<>();
        conta = new javax.swing.JComboBox<>();
        lancamento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        PainelPrincipal6.setBackground(new java.awt.Color(255, 255, 255));

        lblLogotipo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogotipo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icones/logo_banco.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Banco MM - MoneyMaker");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        estornar.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        estornar.setText("Estornar");
        estornar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnestornarclick(evt);
            }
        });
        estornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estornarActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente:");

        jLabel3.setText("Conta:");

        jLabel4.setText("Lançamento:");

        nomeCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Selecione -" }));
        nomeCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nomeClienteItemStateChanged(evt);
            }
        });
        nomeCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeClienteFocusLost(evt);
            }
        });
        nomeCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomeClienteMouseClicked(evt);
            }
        });
        nomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteChanged(evt);
            }
        });

        conta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Selecione -" }));
        conta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contaFocusLost(evt);
            }
        });
        conta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contaMouseClicked(evt);
            }
        });
        conta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaSelecionada(evt);
            }
        });

        lancamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Selecione -" }));
        lancamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lancamentoFocusLost(evt);
            }
        });
        lancamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lancamentoMouseClicked(evt);
            }
        });
        lancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancamentoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setText("Estornar um Lançamento");

        javax.swing.GroupLayout PainelPrincipal6Layout = new javax.swing.GroupLayout(PainelPrincipal6);
        PainelPrincipal6.setLayout(PainelPrincipal6Layout);
        PainelPrincipal6Layout.setHorizontalGroup(
            PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(lblLogotipo6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(conta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lancamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(estornar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipal6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(209, 209, 209))
        );
        PainelPrincipal6Layout.setVerticalGroup(
            PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipal6Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLogotipo6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(conta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(163, 163, 163)
                .addGroup(PainelPrincipal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estornar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lancamentoActionPerformed

    private void lancamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lancamentoMouseClicked
        // NADA
    }//GEN-LAST:event_lancamentoMouseClicked

    private void lancamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lancamentoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lancamentoFocusLost

    private void contaSelecionada(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaSelecionada

    }//GEN-LAST:event_contaSelecionada

    private void contaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contaMouseClicked
        resetLancamento();
    }//GEN-LAST:event_contaMouseClicked

    private void contaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contaFocusLost
        // Obtém a conta selecionada
        int indexCliente = nomeCliente.getSelectedIndex();
        int indexConta = conta.getSelectedIndex();

        if (indexConta > 0) {
            resetLancamento();

            // Obtém os lançamentos
            List<Movimentacao> lancs = clientes.get(indexCliente - 1).getConta().get(indexConta - 1).getMovimentacoes();
            // Adiciona os itens no campo Lançamentos
            for (Movimentacao lanc : lancs) {
                lancamento.addItem(lanc.getOperacao() + " N: " + lanc.getNumero() + " Valor: " + lanc.getValor());
            }
        }
    }//GEN-LAST:event_contaFocusLost

    private void clienteChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteChanged

    }//GEN-LAST:event_clienteChanged

    private void nomeClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeClienteMouseClicked
        resetConta();
        resetLancamento();
    }//GEN-LAST:event_nomeClienteMouseClicked

    private void nomeClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeClienteFocusLost

    }//GEN-LAST:event_nomeClienteFocusLost

    private void nomeClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nomeClienteItemStateChanged

        int indexCliente = nomeCliente.getSelectedIndex();

        if (indexCliente > 0) {
            resetConta();

            Cliente cliente = clientes.get(indexCliente - 1);

            try {
                for (Conta c : cliente.getConta()) {
                    conta.addItem("AG: " + c.getAgencia() + " CONTA N: " + c.getNumeroConta());
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(new JFrame(), "Este cliente não possui nenhuma conta!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_nomeClienteItemStateChanged

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        ControlEstornar.cancelar(this, getParentFrame());
    }//GEN-LAST:event_cancelarActionPerformed

    private void estornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estornarActionPerformed

        int indexCliente = nomeCliente.getSelectedIndex();
        int indexConta = conta.getSelectedIndex();
        int indexMovimentacao = lancamento.getSelectedIndex();

        try {
            Movimentacao mov = clientes.get(indexCliente - 1).getConta().get(indexConta - 1).getMovimentacoes().get(indexMovimentacao - 1);

            boolean status = ControlEstornar.estornar(mov);

            if (status) {
                ControlEstornar.cancelar(this, getParentFrame());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Erro ao processar a transação!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_estornarActionPerformed

    private void btnestornarclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnestornarclick
        // TODO add your handling code here:
    }//GEN-LAST:event_btnestornarclick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEstornar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEstornar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEstornar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEstornar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEstornar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPrincipal6;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox<String> conta;
    private javax.swing.JButton estornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> lancamento;
    private javax.swing.JLabel lblLogotipo6;
    private javax.swing.JComboBox<String> nomeCliente;
    // End of variables declaration//GEN-END:variables
}
