/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Gerencia;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author amiltonjunior
 */
public class PaginaInicial extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form PaginaInicial
     */
    public PaginaInicial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerência - Banco MoneyMaker");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(780, 525));
        setMinimumSize(new java.awt.Dimension(780, 525));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PaginaInicial dialog = new PaginaInicial(new JFrame(), true);
                dialog.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                        System.exit(0);
                    }
                });
                
                // Para exibir a interface em formato cross-platform
                /*
                try {
                    UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PaginaInicial.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(PaginaInicial.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(PaginaInicial.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(PaginaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
                */
                
                // JFrames
                FrameBemVindo frameBemVindo = new FrameBemVindo();
                FrameAberturaConta frameAberturaConta = new FrameAberturaConta();
                FrameEstornar frameEstornar = new FrameEstornar();
                FrameBloquearConta frameBloquear = new FrameBloquearConta();
                FrameConfirmAbertura frameConfirmaAbertura = new FrameConfirmAbertura();
                FrameErroAbertura frameErroAbertura = new FrameErroAbertura();
                
                // Define os JFrames pai
                frameAberturaConta.setParentFrame(frameBemVindo);
                frameEstornar.setParentFrame(frameBemVindo);
                frameBloquear.setParentFrame(frameBemVindo);
                frameConfirmaAbertura.setParentFrame(frameBemVindo);
                frameErroAbertura.setParentFrame(frameBemVindo);
                
                // Define os JFrames de abertura de conta e estorno
                frameBemVindo.setFrameAbertura(frameAberturaConta);
                frameBemVindo.setFrameEstornar(frameEstornar);
                frameBemVindo.setFrameBloquear(frameBloquear);
                
                // Define os frames de erro e sucesso
                frameAberturaConta.setSucessFrame(frameConfirmaAbertura);
                frameAberturaConta.setErrorFrame(frameErroAbertura);
                
                // Alinha no centro
                frameBemVindo.setLocationRelativeTo(null);
                frameAberturaConta.setLocationRelativeTo(null);
                frameEstornar.setLocationRelativeTo(null);
                frameBloquear.setLocationRelativeTo(null);
                frameConfirmaAbertura.setLocationRelativeTo(null);
                frameErroAbertura.setLocationRelativeTo(null);
                
                
                // Exibe o JFrame principal
                frameBemVindo.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
